### Cluster config file :
#yaml

PAIRED_END: TRUE
CREATE_SUB_BAMS: FALSE
MAPPING_SUBFOLDER: "speltoides_TrMo_mapping"
TRIM_DIRS: "/home/barrientosm/projects/GE2POP/2024_TRANS_CWR/2024_MANUEL_BARRIENTOS/03_scripts/mapping/GeCKO/Speltoides_FatsQ/gz_files"
REFERENCE: "/home/barrientosm/projects/GE2POP/2024_TRANS_CWR/2024_MANUEL_BARRIENTOS/03_scripts/mapping/GeCKO/Refs/speltoides/speltoides_transcriptome_YANG_2023_mrna.fasta"
BED: ""
BED_MIN_MEAN_COV: ""
BED_MIN_DIST: ""
BED_MIN_LENGTH: ""
MAPPER: "bwa_mem"
SEQUENCING_TECHNOLOGY: ""
EXTRA_MAPPER_OPTIONS: "-t 4"
PICARD_MARKDUPLICATES_OPTIONS: "-MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 1000"
PICARD_MARKDUPLICATES_JAVA_OPTIONS: ""
SAMTOOLS_INDEX_OPTIONS: ""
REMOVE_DUP_MARKDUPLICATES: TRUE
REMOVE_DUP_UMI: FALSE
UMITOOLS_DEDUP_OPTIONS: ""
SAMTOOLS_VIEW_FILTERS1: "-F 256 -F 2048 -f 2"
SAMTOOLS_VIEW_FILTERS2: ""
